### ISSUE TITLE
Needs some updating

### ISSUE THREAD

**Issue by jdmb77** [cwbuecheler/node-tutorial-for-frontend-devs#6]
First off appreciate the work put into this. After following the tut on CloseBrace I ran into a couple of issues. First there are a few packages that are now deprecated

> npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

Removed Jade from package.json and ran:

> npm install pug --save

Renamed .jade files to .pug
Changed debug package version in package.json to latest 3.1.0 and ran:

> npm install

This removed the 2 other deprecation warnings

In app.js there is not a need to require mongod or bodyparser as they are not used in the app.
Just knit picking, but it would be nice if the tut and src were updated to ES6 syntax. I have updated mine and will fork when able to make these updates available to the community. Thanks again for all the hard work and for sharing. Have a great day!

**Comment by cwbuecheler** [comment]
Heya, thanks for this. The reason I haven't converted to Pug is because last time I checked, the express generator scaffolding app still defaults to Jade. It looks like it's finally changed to defaulting to Pug, so I'll update the tutorial when I have a bit of spare time.

Similarly, the last version still required bodyParser. If there's a mongod reference still in there, that's an artifact from a previous version of the tutorial. I'll take a look.

Thanks again!

**Comment by cwbuecheler** [comment]
@iseth What updates are you looking for?

**Comment by iseth** [comment]
Npm update. Like uodating to pug fro jade

**Comment by cwbuecheler** [comment]
@iseth Gotcha. There will be an update to this tutorial coming in early January which switches from Jade to Pug. In the meantime, I don't actually think the syntax changes at all between the two, so you can probably just install Express with Pug and then continue following the tutorial.

**Comment by cwbuecheler** [comment]
@jdmb77 @iseth - for the record, this tutorial is now updated for 2019, including a complete move away from Jade/Pug and to EJS, which I like better anyway.
